urhdtv/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__, template_folder='templates', url_prefix='/index', static_folder='static', static_url_path='file')

from urhdtv.main import views

urhdtv/main/views.py
from urhdtv.main import main

from flask import render_template


@main.route('/')
def index():
    return render_template('index/index.html')

@main.route('apps')
def apps():
    return render_template('index/apps.html', title='Best Application For Iptv Services')

@main.route('packages')
def packages():
    return render_template('index/packages.html', title='Our Packages')

@main.route('privacy')
def privacy():
    return render_template('index/privacy.html', title='Privacy Policy')

@main.route('terms')
def terms():
    return render_template('index/terms.html', title='Terms Of Use')

@main.route('refund')
def refund():
    return render_template('index/refund.html', title='Refund Policy')

@main.route('404')
def not_found():
    return render_template('index/404.html', title='Not Found !')

urhdtv/main/templates/index/apps.html
{% extends "layout.html" %}
{% block content %}
<br>
    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Applications Recommand </h1>
          <p class="lead text-muted">Here will be found thes best applications in the word for iptv services , we recommand you to use it . If you want to download our application just click the link below .</p>
          <p>
            <a href="https://play.google.com/store/apps/details?id=com.myspecial.launcher.nasaiptv&hl=fr" class="btn btn-primary my-2">NASA-IPTV</a>
          </p>

        </div>
      </section>

      <div class="album py-5 bg-light">
        <div class="container">

          <div class="row">
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
              <img src="{{ url_for('main.static', filename='file/img/apps/1.png') }}" alt="img" class="img-thumbnail">
                <div class="card-body">
                  <p class="card-text">Play your OTT and IPTV streams on Android TV.The application does not contain any channels, you have to add your own.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">


                     <a href="https://play.google.com/store/apps/details?id=eu.siptv.video" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Download</a>
                    <a href="http://siptv.eu/activation/" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Website</a>
                    </div>
              
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img src="https://www.live-tv.store/wp-content/uploads/2017/12/gsesmartiptv-300x300.png" alt="img" class="img-thumbnail">
                <div class="card-body">
                  <p class="card-text">XTREAM-CODES API API support automatic live and VOD playlist including EPG and movie info. Support : AUTOMATIC LIVE STREAM RECONNECTION.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                    <a href="http://gsetechnology.co.uk/apk/gseiptv45.apk" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Download</a>
                    <a href="http://gsesmartiptv.com/" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Website</a>
                    
          
                    </div>
           
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img src="{{ url_for('main.static', filename='file/img/apps/gs.jpg') }}" alt="img" class="img-thumbnail">
                <div class="card-body">
                  <p class="card-text">Watch IPTV from your Internet service provider or free live TV channels from any other source in the web.If you are using VLC to watch TV on your PC then this app is for you..</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                     <a href="https://play.google.com/store/apps/details?id=ru.iptvremote.android.iptv&hl=fr" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Download</a>
                    <a href="#" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Website</a>
                    </div>
            
                  </div>
                </div>
              </div>
            </div>

            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img src="{{ url_for('main.static', filename='file/img/apps/2.png') }}" alt="img" class="img-thumbnail">
                <div class="card-body">
                  <p class="card-text">VLC media player is a free and open source cross-platform multimedia player that plays most multimedia files as well as discs, devices, and network streaming protocols.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                     <a href="https://www.videolan.org/vlc/#download" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Download</a>
                     <a href="https://www.videolan.org/vlc/" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Website</a>
                    </div>
            
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img src="{{ url_for('main.static', filename='file/img/apps/3.jpg') }}" alt="img" class="img-thumbnail">
                <div class="card-body">
                  <p class="card-text">MX Player est un outil de lecture vidéo qui vous permettra de regarder presque n'importe quel film, peu importe son format, sur l'écran de votre appareil Android.</p>
                 <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                  <a href="https://mx-player.fr.uptodown.com/android" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Download</a>
                  <a href="https://mxplayerdownload.co/" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Website</a>
                    </div>
                    
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
               <img src="{{ url_for('main.static', filename='file/img/apps/4.png') }}" alt="img" class="img-thumbnail">
                <div class="card-body">
                  <p class="card-text">this application not contains any streams, graphics or info of streaming Application fully connecting to users XtreamCodes server API.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                     <a href="https://play.google.com/store/apps/details?id=com.niklabs.pp.xtreamcodes2" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Download</a>
                    <a href="https://xtream-codes.com/" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Website</a>
                   
                  </div>
                </div>
              </div>
            </div>

            

    </main>

</div>
</div>
</body>
</script>
</head>
</html>
{% endblock content %}

urhdtv/main/templates/index/index.html
{% extends "layout.html" %}
{% block content %}
<br>
<div id="carousel-example-2" class="carousel slide carousel-fade" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-2" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-2" data-slide-to="1"></li>
        <li data-target="#carousel-example-2" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
            <div class="view">
                <img class="d-block w-100" src="{{ url_for('main.static', filename='file/img/caro1.jpg') }}" alt="First slide">
                <div class="mask rgba-black-slight"></div>
            </div>
            <div class="carousel-caption">
                <h3 class="h3-responsive" style="background-color: #fa9315;">Worldwide Channels</h3>
                <p style="color: black;background-color: white;">
                  We Offer more than 5000 worldwide channels , also multi country packages [Mr,Fr,Uk,Ar,Nl,Sp,Us,Ps...]
                </p>
            </div>
        </div>
        <div class="carousel-item">
            <div class="view">
                <img class="d-block w-100" src="{{ url_for('main.static', filename='file/img/caro2.jpg') }}" alt="Second slide">
                <div class="mask rgba-black-slight"></div>
            </div>
            <div class="carousel-caption">
                <h3 class="h3-responsive" style="background-color: #fa9315;">Auto Configuration</h3>
              <p style="color: black;background-color: white;">
                  we offer auto configure for your device , [ Smart tv,receiver,Computer,Tvbox... ]
                </p>
            </div>
        </div>
        <div class="carousel-item">
            <div class="view">
                <img class="d-block w-100" src="{{ url_for('main.static', filename='file/img/caro3.jpg') }}" alt="Third slide">
                <div class="mask rgba-black-slight"></div>
            </div>
            <div class="carousel-caption">
                <h3 class="h3-responsive" style="background-color: #fa9315;">Full access reseller</h3>
                <p style="color: black;background-color: white;">
                  We offer control panel (Xtream-codes) for our reseller to manage their clients subscriptions ...
                </p>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carousel-example-2" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-2" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="divider-new pt-3">
<center>
<h2 class="h2-responsive indigo-text mx-4 font-bold wow fadeIn">Why is it so great?</h2>
</center>
</div>
<section class="section feature-box text-center">
<p class="section-description lead grey-text mb-5 mx-lg-5">We promise our clients to offer the best iptv services in the world,also availablity to testing it before pay, and adding prefer packages.</p>
<div class="row text-center">
<div class="col-md-4 mb-r">
<img src="{{ url_for('main.static', filename='file/img/powerful.png') }}" alt="p1" class="img-thumbnail">
<h5 class="font-bold mt-3">Powerful</h5>
<p class="grey-text">Powerful servers and load balancers over Europe.We support MAG, Android, iOS, XBMC/KODI, Enigma, PC, Smart TV and more....
</p>
</div>
<div class="col-md-4 mb-r">
<img src="{{ url_for('main.static', filename='file/img/support.png') }}" alt="p1" class="img-thumbnail">
<h5 class="font-bold mt-3">Support</h5>
<p class="grey-text">We offer full support to our clients 24/7,also we can add any channels you want.</p>
</div>
<div class="col-md-4 mb-r">
<img src="{{ url_for('main.static', filename='file/img/back.png') }}" alt="p1" class="img-thumbnail">
<h5 class="font-bold mt-3">Relax</h5>
<p class="grey-text">Money back guaranty ,before limite of the peride after purchase 10 Days</p>
</div>
</div>
</section>
<div class="container">
<center>
<div class="alert alert-warning" role="alert">
Our Plans 
</div>
</center>
<div class="pricing-5 section-gray">
<div class="container">
<div class="row">
<div class="col-md-3">
<div class="block block-pricing">
<div class="table">
<h6 class="category">Free</h6>
<img src="{{ url_for('main.static', filename='file/img/free.png') }}" alt="placeholder." class="img-thumbnail">
<h3 class="block-caption">$00</h3>
<p class="block-description"> If you wanna try our services before pay, just request here.</p> <a href="{{ url_for('authentication.area') }}" class="btn btn-warning btn-round">Get Free</a> </div>
</div>
</div>
<div class="col-md-3">
<div class="block block-pricing">
<div class="table">
<h6 class="category">Pro</h6>
<img src="{{ url_for('main.static', filename='file/img/3000.gif') }}" alt="p1" class="img-thumbnail">
<h3 class="block-caption">$50</h3>
<p class="block-description"> Watch more than 3000 channels with full support  .</p> <a href="{{ url_for('authentication.area') }}" class="btn btn-warning btn-round">Get Started</a> </div>
</div>
</div>
<div class="col-md-3">
<div class="block block-pricing block-raised">
<div class="table table-warning">
<h6 class="category">Premium</h6>
<img src="{{ url_for('main.static', filename='file/img/4000.gif') }}" alt="p1" class="img-thumbnail">
<h3 class="block-caption">$80</h3>
<p class="block-description"> Watch more than 4000 channels with full support.</p> <a href="{{ url_for('authentication.area') }}" class="btn btn-white btn-round">Get Premium</a> </div>
</div>
</div>
<div class="col-md-3">
<div class="block block-pricing">
<div class="table">
<h6 class="category">Reseller</h6>
<img src="{{ url_for('main.static', filename='file/img/reseler.png') }}" alt="p1" class="img-thumbnail">
<h3 class="block-caption">$25</h3>
<p class="block-description"> We offer controle panel, with 10 subscription test / 24H.</p> <a href="#" class="btn btn-warning btn-round">Get Panel</a> </div>
</div>
</div>
</div>
</div>
</div>
<div class="container">
<div class="divider-new pt-5">
<center>
<h2 class="h2-responsive indigo-text mx-4 font-bold wow fadeIn" data-wow-delay="0.2s">
<strong>About us</strong>
</h2>
</center>
</div>
<section id="about" class="text-center wow fadeIn" data-wow-delay="0.2s">
<p>URHD.TV, The best IPTV services in the world, as one of the biggest teams in the internet.That can offer a huge diversity of popular channels live stream from all around the world.</p>
<p>Whenever you do something like buy one of our products, watch a show or download an app, information is created. Because we know your privacy is important, we have a Privacy Policy to explain how we collect, use and protect that informations.</p>
<p>If you have any enquiry just contact us : contact@urhd.tv</p>

</section>
<br>
{% endblock content %}

urhdtv/main/templates/index/privacy.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "layout.html" %}
{% block title %}Privacy Policy{% endblock %}
{% from "_formhelpers.html" import render_field %}
{% block content %}

<div class="page-container" id="PageContainer">
<main class="main-content" id="MainContent" role="main">
<div class="page-width">
<div class="grid">
<div class="grid__item medium-up--five-sixths medium-up--push-one-twelfth">
<div class="section-header text-center">
<br>
<h1>Privacy policy</h1>
</div>
<div class="card">
<div class="card-body">
<div class="container">
  	
Privacy Statement
-----
<br>
<h4>SECTION 1 - WHAT DO WE DO WITH YOUR INFORMATION?</h4>

When you purchase something from our store, as part of the buying and selling process, we collect the personal information you give us such as your name, address and email address. 
When you browse our store, we also automatically receive your computer’s internet protocol (IP) address in order to provide us with information that helps us learn about your browser and operating system. 
Email marketing (if applicable): With your permission, we may send you emails about our store, new products and other updates.
<br>
<h4>SECTION 2 - CONSENT</h4>

How do you get my consent? 
When you provide us with personal information to complete a transaction, verify your credit card, place an order, arrange for a delivery or return a purchase, we imply that you consent to our collecting it and using it for that specific reason only. 
If we ask for your personal information for a secondary reason, like marketing, we will either ask you directly for your expressed consent, or provide you with an opportunity to say no.

How do I withdraw my consent? 
If after you opt-in, you change your mind, you may withdraw your consent for us to contact you, for the continued collection, use or disclosure of your information, at anytime, by contacting us at contact@urhd.tv or mailing us at: 
Urhd.tv 
Egypt-Alexandria Alexandria Alexandria EG 21998
<br>
<h4>SECTION 3 - DISCLOSURE</h4>

We may disclose your personal information if we are required by law to do so or if you violate our Terms of Service.

Payment: 
If you choose a direct payment gateway to complete your purchase, then Shopify stores your credit card data. It is encrypted through the Payment Card Industry Data Security Standard (PCI-DSS). Your purchase transaction data is stored only as long as is necessary to complete your purchase transaction. After that is complete, your purchase transaction information is deleted. 
All direct payment gateways adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. 
PCI-DSS requirements help ensure the secure handling of credit card information by our store and its service providers. 
For more insight, you may also want to read Shopify’s Terms of Service (https://www.stripe.com/legal/terms) or Privacy Statement (https://www.shopify.com/legal/privacy).

Links 
When you click on links on our store, they may direct you away from our site. We are not responsible for the privacy practices of other sites and encourage you to read their privacy statements.
<br>
<h4>SECTION 6 - SECURITY</h4>

To protect your personal information, we take reasonable precautions and follow industry best practices to make sure it is not inappropriately lost, misused, accessed, disclosed, altered or destroyed. 
If you provide us with your credit card information, the information is encrypted using secure socket layer technology (SSL) and stored with a AES-256 encryption. Although no method of transmission over the Internet or electronic storage is 100% secure, we follow all PCI-DSS requirements and implement additional generally accepted industry standards.
<br>
<h4>SECTION 7 - COOKIES</h4>

Here is a list of cookies that we use. We’ve listed them here so you that you can choose if you want to opt-out of cookies or not. 
_session_id, unique token, sessional, Allows Shopify to store information about your session (referrer, landing page, etc). 
_shopify_visit, no data held, Persistent for 30 minutes from the last visit, Used by our website provider’s internal stats tracker to record the number of visits 
_shopify_uniq, no data held, expires midnight (relative to the visitor) of the next day, Counts the number of visits to a store by a single customer. 
cart, unique token, persistent for 2 weeks, Stores information about the contents of your cart. 
_secure_session_id, unique token, sessional 
storefront_digest, unique token, indefinite If the shop has a password, this is used to determine if the current visitor has access.
<br>
<h4>SECTION 8 - AGE OF CONSENT</h4>

By using this site, you represent that you are at least the age of majority in your state or province of residence, or that you are the age of majority in your state or province of residence and you have given us your consent to allow any of your minor dependents to use this site.
<br>
<h4>SECTION 9 - CHANGES TO THIS PRIVACY POLICY</h4>

We reserve the right to modify this privacy policy at any time, so please review it frequently. Changes and clarifications will take effect immediately upon their posting on the website. If we make material changes to this policy, we will notify you here that it has been updated, so that you are aware of what information we collect, how we use it, and under what circumstances, if any, we use and/or disclose it. 
If our store is acquired or merged with another company, your information may be transferred to the new owners so that we may continue to sell products to you.
<br>
<h4>QUESTIONS AND CONTACT INFORMATION</h4>

If you would like to: access, correct, amend or delete any personal information we have about you, register a complaint, or simply want more information contact our Privacy Compliance Officer at contact@urhd.tv or by mail at 
Urhd.tv
</div>
</div>
</div>
</div>
</div>
</main>
</div>
</div>
</div>
{% endblock %}

urhdtv/main/templates/index/refund.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "layout.html" %}
{% block title %}Refund Policy{% endblock %}
{% from "_formhelpers.html" import render_field %}
{% block content %}

<div class="page-container" id="PageContainer">
<main class="main-content" id="MainContent" role="main">
<div class="page-width">
<div class="grid">
<div class="grid__item medium-up--five-sixths medium-up--push-one-twelfth">
<div class="section-header text-center">
<br>
<h1>Refund Policy</h1>
</div>
<div class="card">
<div class="card-body">
<div class="container">

Refund Policy
-----
<br>
Returns 
Our policy lasts 30 days. If 30 days have gone by since your purchase, unfortunately we can’t offer you a refund or exchange.
</div>
</div>
</div>
</div>
</div>
</main>
</div>
</div>
</div>

{% endblock %}

urhdtv/main/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
    <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Antic" rel="stylesheet">
  <link href="{{ url_for('main.static', filename='file/css/pricing.css') }}" rel="stylesheet" media="screen">
  <link href="{{ url_for('main.static', filename='file/css/style.css') }}" rel="stylesheet" media="screen">
  <link href="{{ url_for('main.static', filename='file/css/register.css') }}" rel="stylesheet" media="screen">
  <link rel="shortcut icon" href="{{ url_for('main.static', filename='file/img/favicon.ico') }}">
     <!-- Meta Tags -->
  <meta name="Description" content="Buy best iptv services and watch live stream channels for free" />
  <meta name="keywords" lang="us" content="urhd.tv,live stream,urhd blog,buy iptv,iptv,best iptv,urhd iptv">
  <meta property="og:locale" content="en_US" />
  <meta property="og:type" content="website" />
  <meta property="fb" content="urhd.tv" />
  <meta property="og:site_name" content="www.urhd.tv" />
  <meta name="robots" content="index, follow"/>
  <meta name="apple-mobile-web-app-capable" content="yes">
    {% if title %}
        <title>URHD.TV - {{ title }}</title>
    {% else %}
        <title>URHD.TV</title>
    {% endif %}
 </head>
 <body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <div class="logo"><a href="{{ url_for('main.index') }}"><img src="{{ url_for('authentication.static', filename='img/logo.png') }}" alt="logo"></a></div>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('blog.index') }}"><i class="fas fa-newspaper"></i> News</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('livestream.index') }}"><i class="fas fa-coffee"></i> Livestream</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('main.apps') }}"><i class="fas fa-cloud-download-alt"></i> Application</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('authentication.login') }}"><i class="fas fa-sign-in-alt"></i> Clients Area</a>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if current_user.is_authenticated %}
      <div class="dropdown show">
  <a class="btn btn-secondary dropdown-toggle" href="{{ url_for('authentication.area') }}" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fa fa-user"></i>  Hi, {{ current_user.username }}!
  </a>

  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <a class="dropdown-item" href="#">Profile</a>
    <a class="dropdown-item" href="{{ url_for('authentication.logout') }}">Logout</a>
  </div>
</div>

      {% endif %}
</nav>
<main>
<div class="container">
      {% block content %}{% endblock content %}
</div>

<br>
<footer class="container">
<center>
    <a href="{{ url_for('main.privacy') }}" target="_blank">Privacy policy</a>

    <a href="{{ url_for('main.refund') }}" target="_blank">Refund Policy</a>

    <a href="{{ url_for('main.terms') }}" target="_blank">Terms of service</a>
<p>Copyright © URHD.TV [ Beta v ] 2017-2018</p>
</footer>
    <!-- Optional JavaScript -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>