urhdtv/administrator/__init__.py
from flask import Blueprint

administrator = Blueprint('administrator', __name__, template_folder='templates', url_prefix='/auth', static_folder='static')


from urhdtv.administrator import views

urhdtv/administrator/views.py
from urhdtv.administrator import administrator
#from flask_security.decorators import roles_required
from flask import abort, render_template, g, url_for, flash, redirect
from flask_login import current_user, login_required
from urhdtv.authentication.models import User, Trial, Role
#from flask_principal import Principal, Permission, RoleNeed
from flask_dance.contrib.google import google

# Create a permission with a single Need, in this case a RoleNeed.
 #admin_permission = Permission(RoleNeed('administrator'))



@administrator.route('/dashboard')
#@admin_permission.require()

def admin_dashboard():

	if not google.authorized:
		return redirect(url_for("google.login"))
	resp = google.get("/oauth2/v2/userinfo")
	assert resp.ok, resp.text
	return "You are {email} on Google".format(email=resp.json()["email"])



	return render_template('auth/dashboard.html', title="Dashboard")


@administrator.route('/trial')

def trial():

	#with admin_permission.require():

		#trials = Trial.query.all()

	return render_template('auth/trial.html', trials=trials, title="Trials Request")


@administrator.route('/datas')

def datas():

	#with admin_permission.require():

		#clients = User.query.all()

	return render_template('auth/datas.html', clients=clients, title="Clients Registred")

urhdtv/administrator/templates/_layout_.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
  
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

<link href="{{ url_for('administrator.static', filename='css/sb-admin.css') }}" rel="stylesheet" media="screen">
<link href="{{ url_for('administrator.static', filename='css/calendar.css') }}" rel="stylesheet" media="screen">
<link href="{{ url_for('administrator.static', filename='css/table.css') }}" rel="stylesheet" media="screen">
<link href="{{ url_for('administrator.static', filename='js/table.js') }}" rel="stylesheet" media="screen">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="Description" content="Buy best iptv services and watch live stream channels for free" />
<meta name="keywords" lang="us" content="urhd.tv,live stream,urhd blog,buy iptv,iptv,best iptv,urhd iptv">
<meta property="og:locale" content="en_US" />
<meta property="og:type" content="website" />
<meta property="fb" content="urhd.tv" />
<meta property="og:site_name" content="www.urhd.tv" />
<meta name="robots" content="index, follow"/>
<meta name="apple-mobile-web-app-capable" content="yes">

{% if title %}
<title>URHD.TV - {{ title }}</title>
{% else %}
<title>URHD.TV</title>
{% endif %}

<body id="page-top">
  {% block navbar %}
<nav class="navbar navbar-expand navbar-dark bg-dark static-top">
<a class="navbar-brand mr-1" href="index.html">URHD.TV DASHBOARD</a>
<button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
<i class="fas fa-bars"></i>
</button>
<!-- Navbar Search -->
<form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
<div class="input-group">
<input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
<div class="input-group-append">
<button class="btn btn-warning" type="button">
<i class="fas fa-search"></i>
</button>
</div>
        </div>
</form>

      <!-- Navbar -->
<ul class="navbar-nav ml-auto ml-md-0">
<li class="nav-item dropdown no-arrow mx-1">
<a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
<i class="fas fa-bell fa-fw"></i>
<span class="badge badge-danger">9+</span>
</a>
<div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
<a class="dropdown-item" href="#">Action</a>
<a class="dropdown-item" href="#">Another action</a>
<div class="dropdown-divider"></div>
<a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
<li class="nav-item dropdown no-arrow mx-1">
<a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
<i class="fas fa-envelope fa-fw"></i>
<span class="badge badge-danger">7</span>
          </a>
<div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
<a class="dropdown-item" href="#">Action</a>
<a class="dropdown-item" href="#">Another action</a>
<div class="dropdown-divider"></div>
<a class="dropdown-item" href="#">Something else here</a>
</div>
</li>
<li class="nav-item dropdown no-arrow">
<a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
<i class="fas fa-user-circle fa-fw"></i>
</a>
<div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
<a class="dropdown-item" href="#">Settings</a>
<a class="dropdown-item" href="#">Activity Log</a>
<div class="dropdown-divider"></div>
<a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
          </div>
        </li>
</ul>

    </nav>
    {% endblock %}

<div id="wrapper">
      <!-- Sidebar -->
<ul class="sidebar navbar-nav">
<li class="nav-item active">
<a class="nav-link" href="{{ url_for('administrator.admin_dashboard') }}">
<i class="fas fa-fw fa-tachometer-alt"></i>
<span>Dashboard</span>
</a>

</li>
<li class="nav-item">
<a class="nav-link" href="{{ url_for('administrator.trial') }}">
<i class="fas fa-fw fa-folder"></i>
<span>Trials Requests</span></a>
          
</li>
<li class="nav-item">
<a class="nav-link" href="{{ url_for('administrator.admin_dashboard') }}">
<i class="fas fa-fw fa-chart-area"></i>
<span>Analytics</span></a>
</li>
<li class="nav-item">
<a class="nav-link" href="{{ url_for('administrator.datas') }}">
<i class="fas fa-fw fa-table"></i>
<span>Clients</span></a>
        </li>
</ul>

<div id="content-wrapper">
<div class="container-fluid">
<!-- Breadcrumbs-->
<ol class="breadcrumb">
<li class="breadcrumb-item">
<a href="#">Dashboard</a>
</li>
<li class="breadcrumb-item active">Overview</li>
</ol>
<!-- Icon Cards-->
<div class="row">
<div class="col-xl-3 col-sm-6 mb-3">
<div class="card text-white bg-primary o-hidden h-100">
<div class="card-body">
<div class="card-body-icon">
<i class="fas fa-fw fa-comments"></i>
</div>
<div class="mr-5">26 New Messages!</div>
</div>
<a class="card-footer text-white clearfix small z-1" href="#">
<span class="float-left">View Details</span>
<span class="float-right">
<i class="fas fa-angle-right"></i>
</span>
</a>
</div>
</div>
<div class="col-xl-3 col-sm-6 mb-3">
<div class="card text-white bg-warning o-hidden h-100">
<div class="card-body">
<div class="card-body-icon">
<i class="fas fa-fw fa-list"></i>
</div>
<div class="mr-5">11 New Tasks!</div>
</div>
<a class="card-footer text-white clearfix small z-1" href="#">
<span class="float-left">View Details</span>
<span class="float-right">
<i class="fas fa-angle-right"></i>
</span>
</a>
</div>
</div>
<div class="col-xl-3 col-sm-6 mb-3">
<div class="card text-white bg-success o-hidden h-100">
<div class="card-body">
<div class="card-body-icon">
<i class="fas fa-fw fa-shopping-cart"></i>
</div>
<div class="mr-5">123 New Orders!</div>
</div>
<a class="card-footer text-white clearfix small z-1" href="#">
<span class="float-left">View Details</span>
<span class="float-right">
<i class="fas fa-angle-right"></i>
</span>
</a>
</div>
</div>
<div class="col-xl-3 col-sm-6 mb-3">
<div class="card text-white bg-danger o-hidden h-100">
<div class="card-body">
<div class="card-body-icon">
<i class="fas fa-fw fa-life-ring"></i>
</div>
<div class="mr-5">13 New Tickets!</div>
</div>
<a class="card-footer text-white clearfix small z-1" href="#">
<span class="float-left">View Details</span>
<span class="float-right">
<i class="fas fa-angle-right"></i>
</span>
</a>
</div>
</div>
</div>

{% block content %}{% endblock content %}

{% block footer %}
<footer class="container">
<center>
    <a href="{{ url_for('main.privacy') }}" target="_blank">Privacy policy</a>

    <a href="{{ url_for('main.refund') }}" target="_blank">Refund Policy</a>

    <a href="{{ url_for('main.terms') }}" target="_blank">Terms of service</a>
<p>Copyright © URHD.TV [ Beta v ] 2017-2018</p>
</footer>

    <!-- Optional JavaScript -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>
{% endblock footer %}