urhdtv/authentication/models.py
from flask_login import UserMixin
from flask_security import RoleMixin, SQLAlchemyUserDatastore
from flask_user import login_required, UserManager, UserMixin, SQLAlchemyAdapter
from werkzeug.security import generate_password_hash, check_password_hash
from urhdtv import db, login_manager
#from flask_dance.consumer.backend.sqla import OAuthConsumerMixin, SQLAlchemyBackend


# Define models
roles_users = db.Table('roles_users',
		db.Column('user_id', db.Integer(), db.ForeignKey('users.id')),
		db.Column('role_id', db.Integer(), db.ForeignKey('role.id')))

class Role(db.Model, RoleMixin):
	id = db.Column(db.Integer(), primary_key=True)
	name = db.Column(db.String(80), unique=True)
	description = db.Column(db.String(255))

	def __init__(self, name):
		self.name = name

class User(UserMixin, db.Model):
	"""
	Create an Client table
	"""
	# Ensures table will be named in plural and not in singular
	# as is the name of the model
	__tablename__ = 'users'

	id = db.Column(db.Integer, primary_key=True)
	email = db.Column(db.String(60), index=True, unique=True)
	username = db.Column(db.String(60), index=True, unique=True)
	password_hash = db.Column(db.String(128))
	clienttype_id = db.Column(db.Integer, db.ForeignKey('clienttypes.id'))
	registed_at = db.Column(db.DateTime())
	active = db.Column(db.Boolean())
	roles = db.relationship('Role', secondary=roles_users,
		backref=db.backref('users', lazy='dynamic'))

	@property
	def password(self):
		"""
		Prevent pasword from being accessed
		"""
		raise AttributeError('password is not a readable attribute.')

	@password.setter
	def password(self, password):
		"""
		Set password to a hashed password
		"""
		self.password_hash = generate_password_hash(password)

	def verify_password(self, password):
		"""
		Check if hashed password matches actual password
		"""
		return check_password_hash(self.password_hash, password)

	#def __init__ (self, email, username, password, active, roles):

	@property
	def is_authenticated(self):
		return True
	@property
	def is_anonymous(self):
		return False
	@property
	def roles(self):
		return self.roles
	@property
	def active(self):
		return True

	def get_id(self):
		return str(self.id)


	def __repr__(self):
		return '<User: {}>'.format(self.email)
	

# Set up user_loader
@login_manager.user_loader
def load_user(user_id):
	return User.query.get(int(user_id))



class Trial(db.Model):

	__tablename__ = 'trials'

	id = db.Column(db.Integer, primary_key=True)
	first_name = db.Column(db.String(60), index=True)
	last_name = db.Column(db.String(60), index=True)
	device_type = db.Column(db.String(60), index=True)
	rec_email = db.Column(db.String(60), index=True, unique=True)
	requested_at = db.Column(db.DateTime())

	def __repr__(self):
		return '<trial: {}>'.format(self.username)

class Clienttype(db.Model):
	"""
	Create a clienttype table
	"""
	__tablename__ = 'clienttypes'

	id = db.Column(db.Integer, primary_key=True)
	name = db.Column(db.String(60), unique=True)
	description = db.Column(db.String(200))
	Users = db.relationship('User', backref='clienttype',
								lazy='dynamic')

	def __repr__(self):
		return '<clienttype: {}>'.format(self.name)

urhdtv/authentication/__init__.py
from flask import Blueprint

authentication = Blueprint('authentication', __name__, template_folder='templates', url_prefix='/users', static_folder='static')


from urhdtv.authentication import views

urhdtv/authentication/views.py
from flask import flash, redirect, render_template, url_for, abort, request
from werkzeug.urls import url_parse
from flask_login import login_required, login_user, logout_user, current_user
from urhdtv.authentication import authentication
from . import authentication
from form import LoginForm, RegistrationForm, TrialsForm
from .. import db
from urhdtv.authentication.models import User, Trial

######################################################################################

@authentication.route('/register', methods=['GET', 'POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.index'))
	form = RegistrationForm()
	if form.validate_on_submit():
		user = User(email=form.email.data,
							username=form.username.data,
							password=form.password.data)

		# add employee to the database
		db.session.add(user)
		db.session.commit()
		flash('You have successfully registered! You may now login.')

		# redirect to the login page
		return redirect(url_for('authentication.login'))

	# load registration template
	return render_template('users/register.html', form=form, title='Register')

@authentication.route('/login', methods=['GET', 'POST'])
def login():
    """
    Handle requests to the /login route
    Log an Client in through the login form
    """
    if current_user.is_authenticated:
		return redirect(url_for('authentication.area'))
    form = LoginForm()
    if form.validate_on_submit():

        # check whether Client exists in the database and whether
        # the password entered matches the password in the database
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None and user.verify_password(form.password.data):
            # log Client in
            login_user(user)

            # redirect to the dashboard page after login
            return redirect(url_for('authentication.area'))

        # when login details are incorrect
        else:
            flash('Invalid email or password.')

    # load login template
    return render_template('users/index.html', form=form, title='Login')
	# ...
######################################################################################

@authentication.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@authentication.route('/area', methods=['GET', 'POST'])
@login_required
def area():

	###----Trial Form ----###

	form = TrialsForm()
	if form.validate_on_submit():
		trial = Trial(first_name=form.first_name.data,
					  last_name=form.last_name.data,
					  device_type=form.device_type.data,
					  rec_email =form.rec_email.data)

		# Add to Database Trials###$ $
		db.session.add(trial)
		db.session.commit()
		flash('GreaT *_* : Your Trial Request will be Sent To your Email before 24H .')

		# resirect to the dashboard
		return redirect(url_for('authentication.area'))

	# load trial template
	return render_template('users/pricing.html', form=form, title='Clients Area')

######################################################################################

urhdtv/authentication/templates/__layout__.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
    <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Antic" rel="stylesheet">

  <link href="{{ url_for('authentication.static', filename='bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" media="screen">
  <link href="{{ url_for('authentication.static', filename='css/my-login.css') }}" rel="stylesheet" media="screen">
  <link href="{{ url_for('authentication.static', filename='css/style.css') }}" rel="stylesheet" media="screen">
  <link href="{{ url_for('authentication.static', filename='css/st-tbls.css') }}" rel="stylesheet" media="screen">
     <!-- Meta Tags -->
  <meta name="Description" content="Buy best iptv services and watch live stream channels for free" />
  <meta name="keywords" lang="us" content="urhd.tv,live stream,urhd blog,buy iptv,iptv,best iptv,urhd iptv">
  <meta property="og:locale" content="en_US" />
  <meta property="og:type" content="website" />
  <meta property="fb" content="urhd.tv" />
  <meta property="og:site_name" content="www.urhd.tv" />
  <meta name="robots" content="index, follow"/>
  <meta name="apple-mobile-web-app-capable" content="yes">
    {% if title %}
        <title>URHD.TV - {{ title }}</title>
    {% else %}
        <title>URHD.TV</title>
    {% endif %}
 </head>

<body>
  {% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <div class="logo"><a href="{{ url_for('main.index') }}"><img src="{{ url_for('authentication.static', filename='img/logo.png') }}" alt="logo"></a></div>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('blog.index') }}"><i class="fas fa-newspaper"></i> News</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('livestream.index') }}"><i class="fas fa-coffee"></i> Livestream</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('main.apps') }}"><i class="fas fa-cloud-download-alt"></i> Application</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('authentication.login') }}"><i class="fas fa-sign-in-alt"></i> Clients Area</a>
      </li>
    </ul>
    </div>
</nav>
{% endblock %}
<br>
<main>
<div class="container">
      {% block content %}{% endblock content %}
</div>


<footer class="container">
<center>
    <a href="{{ url_for('main.privacy') }}" target="_blank">Privacy policy</a>

    <a href="{{ url_for('main.refund') }}" target="_blank">Refund Policy</a>

    <a href="{{ url_for('main.terms') }}" target="_blank">Terms of service</a>
<p>Copyright © URHD.TV [ Beta v ] 2017-2018</p>
</footer>
    <!-- Optional JavaScript -->
<link href="{{ url_for('authentication.static', filename='js/jquery.min.js') }}" rel="stylesheet" media="screen">
<link href="{{ url_for('authentication.static', filename='bootstrap/js/bootstrap.min.js') }}" rel="stylesheet" media="screen">
<link href="{{ url_for('authentication.static', filename='js/my-login.js') }}" rel="stylesheet" media="screen">


</html>

urhdtv/authentication/templates/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

urhdtv/authentication/templates/flashes.html
<!doctype html>
<title>urhd.tv</title>
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
{% block body %}{% endblock %}

urhdtv/authentication/templates/users/forgot.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "__layout__.html" %}
{% from "_formhelpers.html" import render_field %}
{% block title %}Login{% endblock %}
{% block content %}
<br>
<br>
<br>
<body class="my-login-page">
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center align-items-center h-100">
				<div class="card-wrapper">
					<div class="card fat">
						<div class="card-body">
							<h4 class="card-title">Forgot Password</h4>
							<form method="POST">
							 
								<div class="form-group">
									<label for="email">E-Mail Address</label>
									<input id="email" type="email" class="form-control" name="email" value="" required autofocus>
									<div class="form-text text-muted">
										By clicking "Reset Password" we will send a password reset link
									</div>
								</div>

								<div class="form-group no-margin">
									<button type="submit" class="btn btn-primary btn-block">
										Reset Password
									</button>
								</div>
							</form>
						</div>
					</div>
					
				</div>
			</div>
		</div>
	</section>
</body>
</html>
{% endblock %}

urhdtv/authentication/templates/users/index.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "__layout__.html" %}
{% from "_formhelpers.html" import render_field %}
{% block title %}Login{% endblock %}
{% block content %}
<body >
<div class="my-login-page">
<section class="h-100">
<div class="container h-100">
<div class="row justify-content-md-center h-100">
<div class="card-wrapper">
<div class="card fat">
<div class="card-body">
<h4 class="card-title">Login</h4>
<form method="POST">
<br>
{% if error %}
<p class=error><strong>Error:</strong> {{ error }}
{% endif %}
<br>
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class="alert alert-{{ messages.0.0 }}" role="alert">
{% for category, message in messages %}
{{ message }} </br>
{% endfor %}
    </div>
  {% endif %}
{% endwith %}	 
<div class="form-group">

{{ wtf.quick_form(form) }}

<a href="#" class="float-right">
Forgot Password?
</a>
</div>
<div class="margin-top20 text-center">
Don't have an account? <a href="{{ url_for('authentication.register') }}">Create One</a>
</div>
</form>
</div>
</div>
</div>
</div>
</div>
</section>
{% endblock %}

urhdtv/authentication/templates/users/pricing.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_formhelpers.html" import render_field %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
<link href="{{ url_for('authentication.static', filename='css/alert.css') }}" rel="stylesheet" media="screen">
<meta name="apple-mobile-web-app-capable" content="yes">
 <meta name="Description" content="Buy best iptv services and watch live stream channels for free" />
  <meta name="keywords" lang="us" content="urhd.tv,live stream,urhd blog,buy iptv,iptv,best iptv,urhd iptv">
  <meta property="og:locale" content="en_US" />
  <meta property="og:type" content="website" />
  <meta property="fb" content="urhd.tv" />
  <meta property="og:site_name" content="www.urhd.tv" />
  <meta name="robots" content="index, follow"/>
  <meta name="apple-mobile-web-app-capable" content="yes">
{% if title %}
<title>URHD.TV - {{ title }}</title>
{% else %}
<title>URHD.TV</title>
{% endif %}

<nav class="navbar navbar-dark bg-dark">
 <!-- Navbar content -->
<div class="logo"><a href="{{ url_for('main.index') }}"><img src="{{ url_for('authentication.static', filename='img/logo.png') }}" alt="logo"></a></div>
<li class="nav-item">
        <a class="nav-link" href="{{ url_for('main.packages') }}"><i class="fas fa-cube"></i> Packages</a>
      </li>
</nav>
<br>
<div class="container">
	<center>
	{% if error %}
<p class=error><strong>Error:</strong> {{ error }}
{% endif %}
<br>
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class="alert alert-{{ messages.0.0 }}" role="alert">
{% for category, message in messages %}
{{ message }} </br>
{% endfor %}
    </div>
  {% endif %}
{% endwith %}
</center>
<div class="card">
<div class="card-body">

<div class="container">
<div class="row">
	<center>
<div class="error-notice">
<div class="oaerror danger">
<strong>Notice</strong> -  : Trial request valid only for 24H.
</div>
<div class="oaerror info">
<strong>Notice</strong> -  : If You are interesting to be a reseller just see reseller area.
</div>

</div>
</div>
</div>
</div>
</div>
<br>
<div class="container">
	<div class="card">
<div class="card-body">
<p class="h5">Client infos</p>
<div class="alert alert-warning" role="alert">
<h4><i class="fa fa-user"></i> Username : {{ current_user.username }}</h4>
<br>
<h4><i class="fas fa-envelope"></i> Email : {{ current_user.email }} </h4>
<br>
<h4><i class="fas fa-box"></i> Packages :  </h4>
</div>
</div>
</div>
<br>
<p class="h5">Pricing Plans</p>
<div class="container">
<div class="card-deck mb-3 text-center">
<div class="card mb-4 box-shadow">
<div class="card-header">
<h4 class="my-0 font-weight-normal">Free</h4>
</div>
<div class="card-body">

<h1 class="card-title pricing-card-title">$0 <small class="text-muted">/1Day</small></h1>
<ul class="list-unstyled mt-3 mb-4">
<i class="fas fa-tv"></i><li>1800 channels</li>
<li>No full Support</li>
</ul>
<!-- Button to Open the Modal -->
<button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal">
Get Trial
</button>
<!-- The Modal -->
<div class="modal" id="myModal">
<div class="modal-dialog">
<div class="modal-content">
<!-- Modal Header -->
<div class="modal-header">
<h4 class="modal-title"><i class="fas fa-tv"></i> Trial Request</h4>
<button type="button" class="close" data-dismiss="modal">&times;</button>
</div>
<!-- Modal body -->
<div class="modal-body">
<form method="POST"> 
<div class="container"> 
<div class="form-group">
{{ wtf.quick_form(form) }}
</div>
</div>
</form>
</div>
</div>
</div>
</div>
</div>
</div>

<div class="card mb-4 box-shadow">
<div class="card-header">
<h4 class="my-0 font-weight-normal">Pro</h4>
</div>
<div class="card-body">
  <div class="card mb-4 text-white bg-dark">
<h1 class="card-title pricing-card-title">$50 <small class="text-muted">/ yr</small></h1>
<ul class="list-unstyled mt-3 mb-4">
<i class="fas fa-tv"></i><li>3000 channels</li>
<i class="far fa-life-ring"></i><li>Full support</li>
<i class="fas fa-film"></i><li>50 Vod channels</li>
<i class="fas fa-check-circle"></i><li>Money Back Garuanté</li>
</ul>
<button type="button" class="btn btn-warning">Get started</button>
</div>
</div>
</div>
<div class="card mb-4 box-shadow">
<div class="card-header">
<h4 class="my-0 font-weight-normal">Premiuim</h4>
</div>
<div class="card-body">
  <div class="card mb-4 text-white bg-dark">
<h1 class="card-title pricing-card-title">$80 <small class="text-muted">/ yr</small></h1>
<ul class="list-unstyled mt-3 mb-4">
<i class="fas fa-tv"></i><li>4000 channels</li>
<i class="far fa-life-ring"></i><li>Full support</li>
<i class="fas fa-film"></i><li>100 Vod channels</li>
<i class="fas fa-check-circle"></i><li>Money Back Garuanté</li>
</ul>
<button type="button" class="btn btn-warning">Contact us</button>
</div>
</div>
</div>
</div>
<div class="row">
<div class="col-md-8">
<div class="card mb-4 bg-dark text-white">
<img class="card-img" src="{{ url_for('authentication.static', filename='img/reseller.jpg') }}" alt="Card image">
<div class="card-img-overlay">
<h5 class="card-title">Reseller Area</h5>
<p class="card-text">If you are interesting to be a reseller just visite reseller area.</p>
<a href="#" class="btn btn-dark btn-sm">SOON</a>
</div>
</div>
</div>
<div class="col-md-4">
<div class="card mb-4 bg-dark text-white">
<img class="card-img" src="{{ url_for('authentication.static', filename='img/support.jpg') }}" alt="Card image">
<div class="card-img-overlay">
<h5 class="card-title">Support</h5>
<p class="card-text">Here you can opent a ticket if you have any enquiry.</p>
<a href="#" class="btn btn-dark btn-sm">SOON</a>
</div>
</div>
</div>
</div>
<p class="h5">New Offers</p>
<div class="row">
<div class="col-md-4">
<div class="card mb-4">
<img class="card-img-top" src="{{ url_for('authentication.static', filename='img/activation.jpg') }}" alt="Card image cap">
<div class="card-body">
<h5 class="card-title">Activation</h5>
<p class="card-text">Free mac adresse activation of smart iptv app after accepting order.</p>
<a href="h#" class="btn btn-outline-dark btn-sm">SOON</a>
</div>
</div>
</div>
<div class="col-md-4">
<div class="card mb-4 border-dark">
<img class="card-img-top" src="{{ url_for('authentication.static', filename='img/more.jpg') }}" alt="Card image cap">
<div class="card-body">
<h5 class="card-title">More Channels</h5>
<p class="card-text">Here you can request any channels, any packages, you prefer.</p>
<a href="#" class="btn btn-dark btn-sm">SOON</a>
</div>
</div>
</div>
<div class="col-md-4">
<div class="card mb-4 text-white bg-dark">

</div>
</div>
</div>
</div>
<br>
<footer class="container">
<center>
    <a href="{{ url_for('main.privacy') }}" target="_blank">Privacy policy</a>

    <a href="{{ url_for('main.refund') }}" target="_blank">Refund Policy</a>

    <a href="{{ url_for('main.terms') }}" target="_blank">Terms of service</a>
<p>Copyright © URHD.TV [ Beta v ] 2017-2018</p>
</footer>

{% endblock %}
    <!-- Optional JavaScript -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

urhdtv/authentication/templates/users/register.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "__layout__.html" %}
{% block title %}Register{% endblock %}
{% block content %}
<br>
 <body class="my-login-page">
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center h-100">
				<div class="card-wrapper">
					<div class="card fat">
						<div class="card-body">
							<h4 class="card-title">Register</h4>
							<form method="POST">
							 
								<div class="form-group">
									{{ wtf.quick_form(form) }}
								</div>

								<div class="margin-top20 text-center">
									Already have an account? <a href="{{ url_for('authentication.login') }}">Login</a>
								</div>
							</form>
						</div>
					</div>
{% endblock %}

urhdtv/authentication/templates/users/reset.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_formhelpers.html" import render_field %}
{% extends "__layout__.html" %}
{% block title %}Login{% endblock %}
{% block content %}
<br>
<body class="my-login-page">
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center align-items-center h-100">
				<div class="card-wrapper">
					<div class="card fat">
						<div class="card-body">
							<h4 class="card-title">Reset Password</h4>
							<form method="POST">
							 
								<div class="form-group">
									<label for="new-password">New Password</label>
									<input id="new-password" type="password" class="form-control" name="password" required autofocus data-eye>
									<div class="form-text text-muted">
										Make sure your password is strong and easy to remember
									</div>
								</div>

								<div class="form-group no-margin">
									<button type="submit" class="btn btn-primary btn-block">
										Reset Password
									</button>
								</div>
							</form>
						</div>
					</div>
					
				</div>
			</div>
		</div>
	</section>
</body>
</html>
{% endblock %}